package de.traveltogether;

/**
 * Created by Anna-Lena on 16.05.2016.
 */
public enum ActionType {
    LIST, DETAIL, ADD, UPDATE, DELETE, REGISTER, LOGIN, GETSALT, RESIGN, GETPARTICIPANTS, ACCEPT, DECLINE, INVITE, GETSTATISTIC, GETNOTICOUNT, GETTITLE, UPDATEDEVICEID, UPDATEPASSWORD
}
