package de.traveltogether;


public enum ActionType {
    LIST, DETAIL, ADD, UPDATE, DELETE, REGISTER, LOGIN, GETSALT, RESIGN, GETPARTICIPANTS, ACCEPT, DECLINE, INVITE, GETSTATISTIC, GETNOTICOUNT, GETTITLE, UPDATEDEVICEID, UPDATEPASSWORD, FORGOTPASSWORD
}
